DECLARE project_id STRING DEFAULT 'your-production-project';
DECLARE dataset_name STRING DEFAULT 'prod_hotel_analytics';
DECLARE table_name STRING DEFAULT 'bookingdata_consortia';

EXECUTE IMMEDIATE FORMAT("""
  CREATE OR REPLACE TABLE `%s.%s.%s` (
    property_code STRING OPTIONS(description='Standardized property_code.'),
    pms_status STRING OPTIONS(description='Standardized pms_status.'),
    book_date TIMESTAMP OPTIONS(description='Standardized book_date.'),
    arrival_date TIMESTAMP OPTIONS(description='Standardized arrival_date.'),
    no_resvn INT64 OPTIONS(description='Standardized no_resvn.'),
    no_nights FLOAT64 OPTIONS(description='Standardized no_nights.'),
    adr FLOAT64 OPTIONS(description='Standardized adr.'),
    rev_stay FLOAT64 OPTIONS(description='Standardized rev_stay.'),
    rev_total FLOAT64 OPTIONS(description='Standardized rev_total.'),
    std_ratecode STRING OPTIONS(description='Standardized std_ratecode.'),
    std_ratecode_name STRING OPTIONS(description='Standardized std_ratecode_name.'),
    std_segment_code STRING OPTIONS(description='Standardized std_segment_code.'),
    std_segment_name STRING OPTIONS(description='Standardized std_segment_name.'),
    std_segment_sort STRING OPTIONS(description='Standardized std_segment_sort.'),
    std_segment_label STRING OPTIONS(description='Standardized std_segment_label.'),
    consortia_code STRING OPTIONS(description='Standardized consortia_code.'),
    consortia_segment STRING OPTIONS(description='Standardized consortia_segment.'),
    consortia_category STRING OPTIONS(description='Standardized consortia_category.'),
    roomtype_code_map STRING OPTIONS(description='Standardized roomtype_code_map.'),
    roomtype_name_map STRING OPTIONS(description='Standardized roomtype_name_map.'),
    roomtype_class_map STRING OPTIONS(description='Standardized roomtype_class_map.'),
    roomtype_category_map STRING OPTIONS(description='Standardized roomtype_category_map.'),
    roomtype_category_name_map STRING OPTIONS(description='Standardized roomtype_category_name_map.'),
    roomtype_available_rms_map STRING OPTIONS(description='Standardized roomtype_available_rms_map.'),
    roomtype_sort STRING OPTIONS(description='Standardized roomtype_sort.'),
    company STRING OPTIONS(description='Standardized company.'),
    corp_profile_name STRING OPTIONS(description='Standardized corp_profile_name.'),
    corp_code STRING OPTIONS(description='Standardized corp_code.'),
    iata STRING OPTIONS(description='Standardized iata.'),
    ta_agency_name STRING OPTIONS(description='Standardized ta_agency_name.'),
    channel_group_code STRING OPTIONS(description='Standardized channel_group_code.'),
    channel_group STRING OPTIONS(description='Standardized channel_group.'),
    channel_code STRING OPTIONS(description='Standardized channel_code.'),
    channel STRING OPTIONS(description='Standardized channel.'),
    channel_sort FLOAT64 OPTIONS(description='Standardized channel_sort.'),
    source_code STRING OPTIONS(description='Standardized source_code.'),
    source STRING OPTIONS(description='Standardized source.'),
    source_sort FLOAT64 OPTIONS(description='Standardized source_sort.'),
    subsource_code STRING OPTIONS(description='Standardized subsource_code.'),
    subsource STRING OPTIONS(description='Standardized subsource.'),
    snapshot_date TIMESTAMP OPTIONS(description='Standardized snapshot_date.'),
    agency_corp_profile_name STRING OPTIONS(description='Standardized agency_corp_profile_name.'),
    agency_corporate_code STRING OPTIONS(description='Standardized agency_corporate_code.'),
    consortia STRING OPTIONS(description='Standardized consortia.'),
    consortia_short_name STRING OPTIONS(description='Standardized consortia_short_name.'),
    agency_rate_type STRING OPTIONS(description='Standardized agency_rate_type.'),
    sent_to_big_query BOOL OPTIONS(description='Standardized sent_to_big_query.'),
    date_sent_to_big_query TIMESTAMP OPTIONS(description='Standardized date_sent_to_big_query.'),
    ingested_timestamp TIMESTAMP OPTIONS(description='Standardized ingested_timestamp.')
  )
""", project_id, dataset_name, table_name);