DECLARE project_id STRING DEFAULT 'your-production-project';
DECLARE dataset_name STRING DEFAULT 'prod_hotel_analytics';
DECLARE table_name STRING DEFAULT 'pace_segment';

EXECUTE IMMEDIATE FORMAT("""
  CREATE OR REPLACE TABLE `%s.%s.%s` (
    property_code STRING OPTIONS(description='Standardized property_code.'),
    property_name STRING OPTIONS(description='Standardized property_name.'),
    physical_capacity INT64 OPTIONS(description='Standardized physical_capacity.'),
    property_shortname STRING OPTIONS(description='Standardized property_shortname.'),
    segment STRING OPTIONS(description='Standardized segment.'),
    dow STRING OPTIONS(description='Standardized dow.'),
    stay_date DATE OPTIONS(description='Standardized stay_date.'),
    stay_date_ly DATE OPTIONS(description='Standardized stay_date_ly.'),
    rms_fct_ly INT64 OPTIONS(description='Standardized rms_fct_ly.'),
    rms_fct INT64 OPTIONS(description='Standardized rms_fct.'),
    adr_fct_ly FLOAT64 OPTIONS(description='Standardized adr_fct_ly.'),
    adr_fct FLOAT64 OPTIONS(description='Standardized adr_fct.'),
    rev_fct FLOAT64 OPTIONS(description='Standardized rev_fct.'),
    rev_fct_ly FLOAT64 OPTIONS(description='Standardized rev_fct_ly.'),
    rms INT64 OPTIONS(description='Standardized rms.'),
    rms_ly INT64 OPTIONS(description='Standardized rms_ly.'),
    rms_stly INT64 OPTIONS(description='Standardized rms_stly.'),
    rms_st2y INT64 OPTIONS(description='Standardized rms_st2y.'),
    rms_st19 INT64 OPTIONS(description='Standardized rms_st19.'),
    adr_ly FLOAT64 OPTIONS(description='Standardized adr_ly.'),
    adr FLOAT64 OPTIONS(description='Standardized adr.'),
    rev FLOAT64 OPTIONS(description='Standardized rev.'),
    rev_ly FLOAT64 OPTIONS(description='Standardized rev_ly.'),
    rev_stly FLOAT64 OPTIONS(description='Standardized rev_stly.'),
    projected_rev FLOAT64 OPTIONS(description='Standardized projected_rev.'),
    projected_rev_ly FLOAT64 OPTIONS(description='Standardized projected_rev_ly.'),
    rev_st2y FLOAT64 OPTIONS(description='Standardized rev_st2y.'),
    rev_st19 FLOAT64 OPTIONS(description='Standardized rev_st19.'),
    arrivals INT64 OPTIONS(description='Standardized arrivals.'),
    arrivals_ly INT64 OPTIONS(description='Standardized arrivals_ly.'),
    projected_rms FLOAT64 OPTIONS(description='Standardized projected_rms.'),
    projected_rms_ly FLOAT64 OPTIONS(description='Standardized projected_rms_ly.'),
    departures INT64 OPTIONS(description='Standardized departures.'),
    departures_ly INT64 OPTIONS(description='Standardized departures_ly.'),
    no_show INT64 OPTIONS(description='Standardized no_show.'),
    no_show_ly INT64 OPTIONS(description='Standardized no_show_ly.'),
    cx INT64 OPTIONS(description='Standardized cx.'),
    cx_ly INT64 OPTIONS(description='Standardized cx_ly.'),
    bgt_rms FLOAT64 OPTIONS(description='Standardized bgt_rms.'),
    bgt_rms_ly FLOAT64 OPTIONS(description='Standardized bgt_rms_ly.'),
    bgt_rev FLOAT64 OPTIONS(description='Standardized bgt_rev.'),
    bgt_rev_ly FLOAT64 OPTIONS(description='Standardized bgt_rev_ly.'),
    segment_code STRING OPTIONS(description='Standardized segment_code.'),
    segment_sort INT64 OPTIONS(description='Standardized segment_sort.'),
    segment_group STRING OPTIONS(description='Standardized segment_group.'),
    segment_group_code STRING OPTIONS(description='Standardized segment_group_code.'),
    finance_segment STRING OPTIONS(description='Standardized finance_segment.'),
    snapshot_date DATE OPTIONS(description='Standardized snapshot_date.'),
    ingested_timestamp TIMESTAMP OPTIONS(description='Standardized ingested_timestamp.'),
    sent_to_big_query BOOL OPTIONS(description='Standardized sent_to_big_query.'),
    date_sent_to_big_query TIMESTAMP OPTIONS(description='Standardized date_sent_to_big_query.')
  )
""", project_id, dataset_name, table_name);