DECLARE project_id STRING DEFAULT 'your-production-project';
DECLARE dataset_name STRING DEFAULT 'prod_hotel_analytics';
DECLARE table_name STRING DEFAULT 'pace_roomtype';

EXECUTE IMMEDIATE FORMAT("""
  CREATE OR REPLACE TABLE `%s.%s.%s` (
    property_code STRING OPTIONS(description='Standardized property_code.'),
    property_name STRING OPTIONS(description='Standardized property_name.'),
    physical_capacity INT64 OPTIONS(description='Standardized physical_capacity.'),
    property_shortname STRING OPTIONS(description='Standardized property_shortname.'),
    rms_roomtype STRING OPTIONS(description='Standardized rms_roomtype.'),
    rms_roomtype_class STRING OPTIONS(description='Standardized rms_roomtype_class.'),
    dow STRING OPTIONS(description='Standardized dow.'),
    stay_date DATE OPTIONS(description='Standardized stay_date.'),
    stay_date_ly DATE OPTIONS(description='Standardized stay_date_ly.'),
    rms INT64 OPTIONS(description='Standardized rms.'),
    rms_ly INT64 OPTIONS(description='Standardized rms_ly.'),
    rms_stly INT64 OPTIONS(description='Standardized rms_stly.'),
    rms_st2y INT64 OPTIONS(description='Standardized rms_st2y.'),
    rms_st19 INT64 OPTIONS(description='Standardized rms_st19.'),
    adr FLOAT64 OPTIONS(description='Standardized adr.'),
    adr_ly FLOAT64 OPTIONS(description='Standardized adr_ly.'),
    adr_fct_ly FLOAT64 OPTIONS(description='Standardized adr_fct_ly.'),
    adr_fct FLOAT64 OPTIONS(description='Standardized adr_fct.'),
    rev FLOAT64 OPTIONS(description='Standardized rev.'),
    rev_ly FLOAT64 OPTIONS(description='Standardized rev_ly.'),
    rev_stly FLOAT64 OPTIONS(description='Standardized rev_stly.'),
    rev_st2y FLOAT64 OPTIONS(description='Standardized rev_st2y.'),
    rev_st19 FLOAT64 OPTIONS(description='Standardized rev_st19.'),
    rev_fct FLOAT64 OPTIONS(description='Standardized rev_fct.'),
    rev_fct_ly FLOAT64 OPTIONS(description='Standardized rev_fct_ly.'),
    revpar FLOAT64 OPTIONS(description='Standardized revpar.'),
    revpar_ly FLOAT64 OPTIONS(description='Standardized revpar_ly.'),
    revpar_fct FLOAT64 OPTIONS(description='Standardized revpar_fct.'),
    revpar_fct_ly FLOAT64 OPTIONS(description='Standardized revpar_fct_ly.'),
    rms_other FLOAT64 OPTIONS(description='Standardized rms_other.'),
    rms_other_ly FLOAT64 OPTIONS(description='Standardized rms_other_ly.'),
    arrivals INT64 OPTIONS(description='Standardized arrivals.'),
    arrivals_ly INT64 OPTIONS(description='Standardized arrivals_ly.'),
    departures INT64 OPTIONS(description='Standardized departures.'),
    departures_ly INT64 OPTIONS(description='Standardized departures_ly.'),
    rms_ooo INT64 OPTIONS(description='Standardized rms_ooo.'),
    rms_ooo_ly INT64 OPTIONS(description='Standardized rms_ooo_ly.'),
    cx INT64 OPTIONS(description='Standardized cx.'),
    cx_ly INT64 OPTIONS(description='Standardized cx_ly.'),
    no_show INT64 OPTIONS(description='Standardized no_show.'),
    no_show_ly INT64 OPTIONS(description='Standardized no_show_ly.'),
    capacity INT64 OPTIONS(description='Standardized capacity.'),
    capacity_ly INT64 OPTIONS(description='Standardized capacity_ly.'),
    remaining_capacity INT64 OPTIONS(description='Standardized remaining_capacity.'),
    remaining_capacity_ly INT64 OPTIONS(description='Standardized remaining_capacity_ly.'),
    overbooking INT64 OPTIONS(description='Standardized overbooking.'),
    overbooking_ly INT64 OPTIONS(description='Standardized overbooking_ly.'),
    bar STRING OPTIONS(description='Standardized bar.'),
    bar_ly STRING OPTIONS(description='Standardized bar_ly.'),
    roomtype STRING OPTIONS(description='Standardized roomtype.'),
    roomtype_code STRING OPTIONS(description='Standardized roomtype_code.'),
    roomtype_class STRING OPTIONS(description='Standardized roomtype_class.'),
    roomtype_category_code STRING OPTIONS(description='Standardized roomtype_category_code.'),
    roomtype_category_base STRING OPTIONS(description='Standardized roomtype_category_base.'),
    roomtype_category STRING OPTIONS(description='Standardized roomtype_category.'),
    roomtype_physical_capacity STRING OPTIONS(description='Standardized roomtype_physical_capacity.'),
    roomtype_sort STRING OPTIONS(description='Standardized roomtype_sort.'),
    snapshot_date DATE OPTIONS(description='Standardized snapshot_date.'),
    ingested_timestamp TIMESTAMP OPTIONS(description='Standardized ingested_timestamp.'),
    sent_to_big_query BOOL OPTIONS(description='Standardized sent_to_big_query.'),
    date_sent_to_big_query TIMESTAMP OPTIONS(description='Standardized date_sent_to_big_query.')
  )
""", project_id, dataset_name, table_name);