DECLARE project_id STRING DEFAULT 'your-production-project';
DECLARE dataset_name STRING DEFAULT 'prod_hotel_analytics';
DECLARE table_name STRING DEFAULT 'snap_property';

EXECUTE IMMEDIATE FORMAT("""
  CREATE OR REPLACE TABLE `%s.%s.%s` (
    property_code STRING OPTIONS(description='Standardized property_code.'),
    property_name STRING OPTIONS(description='Standardized property_name.'),
    stay_date DATE OPTIONS(description='Standardized stay_date.'),
    special_events STRING OPTIONS(description='Standardized special_events.'),
    special_events_ly STRING OPTIONS(description='Standardized special_events_ly.'),
    available_rms INT64 OPTIONS(description='Standardized available_rms.'),
    available_rms_ly INT64 OPTIONS(description='Standardized available_rms_ly.'),
    rms_otb INT64 OPTIONS(description='Standardized rms_otb.'),
    rms_ly_act INT64 OPTIONS(description='Standardized rms_ly_act.'),
    rms_stly INT64 OPTIONS(description='Standardized rms_stly.'),
    rms_st2y INT64 OPTIONS(description='Standardized rms_st2y.'),
    rms_rms_fct INT64 OPTIONS(description='Standardized rms_rms_fct.'),
    rev_otb FLOAT64 OPTIONS(description='Standardized rev_otb.'),
    rev_ly_act FLOAT64 OPTIONS(description='Standardized rev_ly_act.'),
    rev_stly FLOAT64 OPTIONS(description='Standardized rev_stly.'),
    rev_st2y FLOAT64 OPTIONS(description='Standardized rev_st2y.'),
    rms_rev_fct FLOAT64 OPTIONS(description='Standardized rms_rev_fct.'),
    transient_rms_otb INT64 OPTIONS(description='Standardized transient_rms_otb.'),
    transient_rms_ly_act INT64 OPTIONS(description='Standardized transient_rms_ly_act.'),
    transient_rms_stly INT64 OPTIONS(description='Standardized transient_rms_stly.'),
    transient_rms_st2y INT64 OPTIONS(description='Standardized transient_rms_st2y.'),
    transient_rev_otb FLOAT64 OPTIONS(description='Standardized transient_rev_otb.'),
    transient_rev_ly_act FLOAT64 OPTIONS(description='Standardized transient_rev_ly_act.'),
    transient_rev_stly FLOAT64 OPTIONS(description='Standardized transient_rev_stly.'),
    transient_rev_st2y FLOAT64 OPTIONS(description='Standardized transient_rev_st2y.'),
    group_rms_otb INT64 OPTIONS(description='Standardized group_rms_otb.'),
    group_rms_ly_act INT64 OPTIONS(description='Standardized group_rms_ly_act.'),
    group_rms_stly INT64 OPTIONS(description='Standardized group_rms_stly.'),
    group_rms_st2y INT64 OPTIONS(description='Standardized group_rms_st2y.'),
    group_rev_otb FLOAT64 OPTIONS(description='Standardized group_rev_otb.'),
    group_rev_ly_act FLOAT64 OPTIONS(description='Standardized group_rev_ly_act.'),
    group_rev_stly FLOAT64 OPTIONS(description='Standardized group_rev_stly.'),
    group_rev_st2y FLOAT64 OPTIONS(description='Standardized group_rev_st2y.'),
    total_demand_total INT64 OPTIONS(description='Standardized total_demand_total.'),
    total_demand_total_ly_act INT64 OPTIONS(description='Standardized total_demand_total_ly_act.'),
    total_demand_group INT64 OPTIONS(description='Standardized total_demand_group.'),
    total_demand_group_ly_act INT64 OPTIONS(description='Standardized total_demand_group_ly_act.'),
    total_demand_transient INT64 OPTIONS(description='Standardized total_demand_transient.'),
    total_demand_transient_ly_act INT64 OPTIONS(description='Standardized total_demand_transient_ly_act.'),
    ooo_rms INT64 OPTIONS(description='Standardized ooo_rms.'),
    ooo_rms_ly INT64 OPTIONS(description='Standardized ooo_rms_ly.'),
    lrv FLOAT64 OPTIONS(description='Standardized lrv.'),
    wash_pct FLOAT64 OPTIONS(description='Standardized wash_pct.'),
    wash_pct_ly_act FLOAT64 OPTIONS(description='Standardized wash_pct_ly_act.'),
    bar_price FLOAT64 OPTIONS(description='Standardized bar_price.'),
    snapshot_date DATE OPTIONS(description='Standardized snapshot_date.')
  )
""", project_id, dataset_name, table_name);